Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 7
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	134	get_ncbi
	135

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000016047.complete
    output: data/ncbi_coords/ENSSSCG00000016047.ncbi
    jobid: 249
    wildcards: id=ENSSSCG00000016047

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000001741.complete
    output: data/ncbi_coords/ENSSSCG00000001741.ncbi
    jobid: 189
    wildcards: id=ENSSSCG00000001741

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000030168.complete
    output: data/ncbi_coords/ENSSSCG00000030168.ncbi
    jobid: 159
    wildcards: id=ENSSSCG00000030168

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000012593.complete
    output: data/ncbi_coords/ENSSSCG00000012593.ncbi
    jobid: 25
    wildcards: id=ENSSSCG00000012593

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000012371.complete
    output: data/ncbi_coords/ENSSSCG00000012371.ncbi
    jobid: 115
    wildcards: id=ENSSSCG00000012371

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000007215.complete
    output: data/ncbi_coords/ENSSSCG00000007215.ncbi
    jobid: 263
    wildcards: id=ENSSSCG00000007215

[Thu Nov 19 17:35:06 2020]
rule get_ncbi:
    input: data/complete_coords/ENSSSCG00000015053.complete
    output: data/ncbi_coords/ENSSSCG00000015053.ncbi
    jobid: 221
    wildcards: id=ENSSSCG00000015053

[Thu Nov 19 17:35:06 2020]
Error in rule get_ncbi:
    jobid: 263
    output: data/ncbi_coords/ENSSSCG00000007215.ncbi

RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmp0kjg_70_.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
[Thu Nov 19 17:35:07 2020]
Error in rule get_ncbi:
    jobid: 249
    output: data/ncbi_coords/ENSSSCG00000016047.ncbi

RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmplqn54cbl.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
[Thu Nov 19 17:35:07 2020]
Error in rule get_ncbi:
    jobid: 25
    output: data/ncbi_coords/ENSSSCG00000012593.ncbi

RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmp4esoocyd.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
[Thu Nov 19 17:35:07 2020]
Error in rule get_ncbi:
    jobid: 221
    output: data/ncbi_coords/ENSSSCG00000015053.ncbi
[Thu Nov 19 17:35:07 2020]

Error in rule get_ncbi:
    jobid: 189
    output: data/ncbi_coords/ENSSSCG00000001741.ncbi

RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmp4f_1i14q.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmpf_mxs6p7.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
[Thu Nov 19 17:35:07 2020]
Error in rule get_ncbi:
    jobid: 115
    output: data/ncbi_coords/ENSSSCG00000012371.ncbi

RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmphrun1sty.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
[Thu Nov 19 17:35:07 2020]
Error in rule get_ncbi:
    jobid: 159
    output: data/ncbi_coords/ENSSSCG00000030168.ncbi

RuleException:
CalledProcessError in line 28 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmppwm3cl72.get_ncbi.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 28, in __rule_get_ncbi
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pelmo/tesi/remap_sscrofa/.snakemake/log/2020-11-19T173506.024330.snakemake.log
