Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	12	verify_vars
	13
Select jobs to execute...

[Wed Dec  2 23:20:08 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000010885.remapped
    output: data/verified_vars/ENSSSCG00000010885.verified
    jobid: 391
    wildcards: id=ENSSSCG00000010885

[Wed Dec  2 23:20:08 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000002756.remapped
    output: data/verified_vars/ENSSSCG00000002756.verified
    jobid: 354
    wildcards: id=ENSSSCG00000002756

[Wed Dec  2 23:20:08 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000011512.remapped
    output: data/verified_vars/ENSSSCG00000011512.verified
    jobid: 310
    wildcards: id=ENSSSCG00000011512

[Wed Dec  2 23:20:08 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000010816.remapped
    output: data/verified_vars/ENSSSCG00000010816.verified
    jobid: 278
    wildcards: id=ENSSSCG00000010816

[Wed Dec  2 23:20:09 2020]
Error in rule verify_vars:
    jobid: 354
    output: data/verified_vars/ENSSSCG00000002756.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpmpwzmc37.var_confirmation.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Terminating processes on user request, this might take some time.
[Wed Dec  2 23:20:12 2020]
Error in rule verify_vars:
    jobid: 391
    output: data/verified_vars/ENSSSCG00000010885.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmppgyyxt8m.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Wed Dec  2 23:20:12 2020]
Error in rule verify_vars:
    jobid: 310
    output: data/verified_vars/ENSSSCG00000011512.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmp6y0_cx3c.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Wed Dec  2 23:20:12 2020]
Error in rule verify_vars:
    jobid: 278
    output: data/verified_vars/ENSSSCG00000010816.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpm43c1xxn.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Complete log: /home/pelmo/sscrofa_variant_remapping/.snakemake/log/2020-12-02T232007.797443.snakemake.log
