Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 7
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	134	merge_results
	135
Select jobs to execute...

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000030227.vars.report, data/complete_coords/ENSSSCG00000030227.complete
    output: data/remapped_vars/ENSSSCG00000030227.remapped
    jobid: 255
    wildcards: id=ENSSSCG00000030227

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000025244.vars.report, data/complete_coords/ENSSSCG00000025244.complete
    output: data/remapped_vars/ENSSSCG00000025244.remapped
    jobid: 15
    wildcards: id=ENSSSCG00000025244

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000004296.vars.report, data/complete_coords/ENSSSCG00000004296.complete
    output: data/remapped_vars/ENSSSCG00000004296.remapped
    jobid: 195
    wildcards: id=ENSSSCG00000004296

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000010780.vars.report, data/complete_coords/ENSSSCG00000010780.complete
    output: data/remapped_vars/ENSSSCG00000010780.remapped
    jobid: 135
    wildcards: id=ENSSSCG00000010780

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000008326.vars.report, data/complete_coords/ENSSSCG00000008326.complete
    output: data/remapped_vars/ENSSSCG00000008326.remapped
    jobid: 1
    wildcards: id=ENSSSCG00000008326

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000011147.vars.report, data/complete_coords/ENSSSCG00000011147.complete
    output: data/remapped_vars/ENSSSCG00000011147.remapped
    jobid: 239
    wildcards: id=ENSSSCG00000011147

[Mon Nov 23 12:56:13 2020]
rule merge_results:
    input: data/var_coords_remapped_report/ENSSSCG00000031060.vars.report, data/complete_coords/ENSSSCG00000031060.complete
    output: data/remapped_vars/ENSSSCG00000031060.remapped
    jobid: 209
    wildcards: id=ENSSSCG00000031060

[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 209
    output: data/remapped_vars/ENSSSCG00000031060.remapped

RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpqkepcygx.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 255
    output: data/remapped_vars/ENSSSCG00000030227.remapped

RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpcl630atx.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 195
    output: data/remapped_vars/ENSSSCG00000004296.remapped

RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpjfi2p006.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 135
    output: data/remapped_vars/ENSSSCG00000010780.remapped

[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 15
    output: data/remapped_vars/ENSSSCG00000025244.remapped

RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpf5m45gl3.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 239
    output: data/remapped_vars/ENSSSCG00000011147.remapped

RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmp8i4ewwtx.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmppjr8saes.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Mon Nov 23 12:56:14 2020]
Error in rule merge_results:
    jobid: 1
    output: data/remapped_vars/ENSSSCG00000008326.remapped

RuleException:
CalledProcessError in line 30 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmp3joj0xg7.merge_results.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 30, in __rule_merge_results
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pelmo/sscrofa_variant_remapping/.snakemake/log/2020-11-23T125613.610702.snakemake.log
