Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 1 (use --cores to define parallelism)
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	134	get_coords
	135

[Fri Nov 13 12:19:17 2020]
rule get_coords:
    input: data/starting_files/ENSSSCG00000015801
    output: data/gene_coords/ENSSSCG00000015801.gene, data/var_coords/ENSSSCG00000015801.vars
    jobid: 28
    wildcards: id=ENSSSCG00000015801

[Fri Nov 13 12:19:17 2020]
Error in rule get_coords:
    jobid: 28
    output: data/gene_coords/ENSSSCG00000015801.gene, data/var_coords/ENSSSCG00000015801.vars

RuleException:
CalledProcessError in line 18 of /home/pelmo/tesi/remap_sscrofa/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/tesi/remap_sscrofa/.snakemake/scripts/tmpyqt4ad9z.get_coords.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2231, in run_wrapper
  File "/home/pelmo/tesi/remap_sscrofa/Snakefile", line 18, in __rule_get_coords
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2262, in run_wrapper
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /home/pelmo/tesi/remap_sscrofa/.snakemake/log/2020-11-13T121916.867726.snakemake.log
