Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	all
	19	verify_vars
	20
Select jobs to execute...

[Wed Dec  2 22:28:56 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000008088.remapped
    output: data/verified_vars/ENSSSCG00000008088.verified
    jobid: 333
    wildcards: id=ENSSSCG00000008088

[Wed Dec  2 22:28:56 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000010554.remapped
    output: data/verified_vars/ENSSSCG00000010554.verified
    jobid: 306
    wildcards: id=ENSSSCG00000010554

[Wed Dec  2 22:28:56 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000010816.remapped
    output: data/verified_vars/ENSSSCG00000010816.verified
    jobid: 278
    wildcards: id=ENSSSCG00000010816

[Wed Dec  2 22:28:56 2020]
rule verify_vars:
    input: data/remapped_vars/ENSSSCG00000001743.remapped
    output: data/verified_vars/ENSSSCG00000001743.verified
    jobid: 272
    wildcards: id=ENSSSCG00000001743

[Wed Dec  2 22:28:57 2020]
Error in rule verify_vars:
    jobid: 333
    output: data/verified_vars/ENSSSCG00000008088.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpysu0ah6e.var_confirmation.py' returned non-zero exit status 1.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Terminating processes on user request, this might take some time.
[Wed Dec  2 22:29:09 2020]
Error in rule verify_vars:
    jobid: 306
    output: data/verified_vars/ENSSSCG00000010554.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpv34g8_qr.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Wed Dec  2 22:29:09 2020]
Error in rule verify_vars:
    jobid: 272
    output: data/verified_vars/ENSSSCG00000001743.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpqcp8lxu1.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
[Wed Dec  2 22:29:09 2020]
Error in rule verify_vars:
    jobid: 278
    output: data/verified_vars/ENSSSCG00000010816.verified

RuleException:
CalledProcessError in line 41 of /home/pelmo/sscrofa_variant_remapping/Snakefile:
Command 'set -euo pipefail;  /home/pelmo/anaconda3/envs/snakemake/bin/python3.9 /home/pelmo/sscrofa_variant_remapping/.snakemake/scripts/tmpqynhujfq.var_confirmation.py' died with <Signals.SIGINT: 2>.
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2273, in run_wrapper
  File "/home/pelmo/sscrofa_variant_remapping/Snakefile", line 41, in __rule_verify_vars
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 560, in _callback
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/concurrent/futures/thread.py", line 52, in run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 546, in cached_or_run
  File "/home/pelmo/anaconda3/envs/snakemake/lib/python3.9/site-packages/snakemake/executors/__init__.py", line 2304, in run_wrapper
Complete log: /home/pelmo/sscrofa_variant_remapping/.snakemake/log/2020-12-02T222855.730341.snakemake.log
